version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: db-unify-postgres
    environment:
      POSTGRES_DB: bootstrapdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-unify-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-unify-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bootstrapdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    networks:
      - db-unify-net

volumes:
  postgres_data:

networks:
  db-unify-net:
